### PR TITLE
update bootsnap gem to support Ruby2.7

### PR DESCRIPTION
**Pull request by yohm**
Because of [this issue](https://github.com/Shopify/bootsnap/issues/258), updating bootsnap gem is required to make it work with Ruby2.7.

### CODE REVIEW

**Comment by yohm** [comment]
To make it work with Ruby2.7, "e2mmap" were added as it was removed from the standard library since Ruby 2.7.0. Other gems were also updated.

**Comment by waiting-for-dev** [comment]
Is it possible to ask for a new release with this addition? :smiley_cat:

**Comment by yohm** [comment]
@waiting-for-dev We've released v3.7.1 which includes this PR.

**Comment by waiting-for-dev** [comment]
Thanks @yohm !

**Pull request merged**
